@startuml
actor Покупатель as C
participant "UI магазина" as UI
participant "Контроль заказов" as OC
participant "Сервис оплаты" as PS
database "База данных" as DB

C -> UI : запрос на оформление заказа
OC -> DB : сохранение данных о заказе
DB --> OC : данные о заказе сохранены в БД
UI -> OC : передача данных в модуль
OC -> PS : оплата заказа
PS --> OC : подтверждение оплаты заказа
OC --> UI : подтверждение заказа
UI --> C : заказ оформлен

@enduml