@startuml
Title Процесс онлайн-перевода между счетами
actor Клиент as c
participant "Мобильное приложение" as app
participant "Бэкенд" as back
database "База данных" as db
participant "СМС-сервис" as sms


c -> app : инциация перевода ДС
app -> back : отправка запроса на перевод ДС
back -> db : проверка наличия ДС
db --> back : результат проверки ДС
alt ДС есть на счёте
db --[#green]> back : подтверждение наличия ДС
else на ДС отсутствуют средства
db --[#red]> back : на счете недостаточно средств
end
back --> app : результат обработки запроса
app --> c : уведмоление клиента

opt Формирование сообщения в случае изменения ЛС
back -> sms : 
end


@enduml