@startuml
[*] --> Карта : подписание договора с банком
state Карта {
[*] --> Активная : выпуск карты
state Активная {
    state Обычная
    Обычная --> Премиум : повышение статуса клиента
    state Премиум
    Премиум --> Обычная : понижение статуса клиента
}
state Заблокированная
Активная --> Заблокированная : попытка мошеничества
Заблокированная --> Активная : разблокировка карты
Утерянная --> Заблокированная : блокировка карты
Заблокированная --> [*] : карта ликвидирована

state Просроченная
Активная --> Просроченная : [таймаут 2 года]
Просроченная --> Активная : срок действия продлён
note right of Просроченная
[таймер] карта переходит в статус "Просрочена"
если срок действия карты истёк
end note
Просроченная --> [*] : карта ликвидирована

state Утерянная
Активная --> Утерянная : сообщение об утрате
Утерянная --> Активная : сообщение о находке

}
Карта --> [*] : закрытие договора по карте

@enduml