@@startuml
|Клиент|
start
:начало сессии клиента;
|Система|
if (пользователь зарегистрирован?) then (нет)
:регистрация клиента;
else (да)
:авторизация клиента;
endif
|Клиент|
:оформление заказа;
fork
:выбор товара;
fork again
:добавление товара в корзину;
endfork

|Система|
if (товар есть в данном кол-ве на остатке?) then (нет)
|Клиент|
fork
:увед. об отсутствии товара;
forkagain
:выбор альтернативного товара;
forkagain
:удалить отсут. из заказа;
endfork
else (да)
|Система|
:форма оплаты заказа;
endif

|Клиент|
:выбор способа оплаты;
fork
:MasterCard;
fork again
:СБП;
fork again
:PayPal;
endfork

|Система|
fork
:проверка платежных данных;
forkagain
:проведение транзакции;
endfork

|Склад|
:подготовка товара к отправке;
fork
:уведомление о необх. сборки заказа;
forkagain
:комплектация заказа по списку;
endfork

|Система|
if (оплата прошла успешно/товар готов к отправке) then (нет)
|Клиент|
fork
:уведомление о проблеме с платежом;
fork again
:повторить попытку оплаты;
forkagain
:изменить способ оплаты;
endfork
if (клиента устроило решение?) then (нет)
|Система|
fork
:отмена заказа;
forkagain
:возврат средств;
endfork
end
endif
else (да)
|Система|
fork
:генерируется счет-фактура;
forkagain
:переход заказа в статус "Отправлен";
forkagain
|Клиент|
:уведомление клиента о подтверждении заказа/статуса доставки;
endfork
endif
|Система|
:товар собран, оплачен и готов к отправке;
|Клиент|
:уведомление клиента об отправке товаров;
end
@@enduml